name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - conda-env: docs-cf
            python-version: 3.6
            label: Generic
            runs-on: ubuntu-latest

          # - conda-env:
          #   python-version:
          #   label:
          #   runs-on: ubuntu-latest

    name: "🐍 ${{ matrix.cfg.python-version }} • ${{ matrix.cfg.label }}"
    runs-on: ${{ matrix.cfg.runs-on }}

    steps:
    - uses: actions/checkout@v2
#      with:
#        fetch-depth: 0

    - name: Create Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        environment-file: devtools/conda-envs/${{ matrix.cfg.conda-env }}.yaml
        python-version: ${{ matrix.cfg.python-version }}
        auto-activate-base: false

    - name: Environment Information
      run: |
        conda info
        conda list --show-channel-urls

    - name: Install QCDB
      run: |
        python -m pip install . --no-deps

    - name: PyTest
      run: |
        pytest -rws -v --cov=qcdb --color=yes --cov-report=xml qcdb/

    - name: CodeCov
      uses: codecov/codecov-action@v1
